Added Starlark tests for macos_dylib rules.
Removed existing tests as these cover the same workflows.

RELNOTES: None.
PiperOrigin-RevId: 314433228

diff --git a/test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template b/test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template
--- a/test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template
+++ b/test/starlark_tests/verifier_scripts/apple_verification_test_runner.sh.template
@@ -20,16 +20,36 @@ set -eu
 source test/unittest.bash
 source test/apple_shell_testutils.sh
 
-# Unzip the archive into a temporary location.
-ARCHIVE_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/bundle_tmp_dir.XXXXXX")"
-trap 'rm -rf "${ARCHIVE_ROOT}"' ERR EXIT
-unzip -qq "%{archive}s" -d "$ARCHIVE_ROOT"
+ARCHIVE_PATH="%{archive}s"
+STANDALONE_BINARY="%{standalone_binary}s"
 
-# Define common bundle locations to be used by the verifier scripts.
-BINARY="$ARCHIVE_ROOT/%{archive_relative_binary}s"
-BUNDLE_ROOT="$ARCHIVE_ROOT/%{archive_relative_bundle}s"
-CONTENT_ROOT="$ARCHIVE_ROOT/%{archive_relative_contents}s"
-RESOURCE_ROOT="$ARCHIVE_ROOT/%{archive_relative_resources}s"
+if [[ -n "$ARCHIVE_PATH" ]]; then
+
+  # Unzip the archive into a temporary location.
+  ARCHIVE_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/bundle_tmp_dir.XXXXXX")"
+
+  trap 'rm -rf "${ARCHIVE_ROOT}"' ERR EXIT
+
+  unzip -qq "$ARCHIVE_PATH" -d "$ARCHIVE_ROOT"
+
+  # Define common bundle locations to be used by the verifier scripts.
+  BINARY="$ARCHIVE_ROOT/%{archive_relative_binary}s"
+  BUNDLE_ROOT="$ARCHIVE_ROOT/%{archive_relative_bundle}s"
+  CONTENT_ROOT="$ARCHIVE_ROOT/%{archive_relative_contents}s"
+  RESOURCE_ROOT="$ARCHIVE_ROOT/%{archive_relative_resources}s"
+
+elif [[ -n "$STANDALONE_BINARY" ]]; then
+
+  # If only a binary was provided instead of an archive, treat that as the root
+  # element for all root "bundle" locations used by the verifier scripts.
+  BINARY="$STANDALONE_BINARY"
+  BUNDLE_ROOT="$STANDALONE_BINARY"
+  CONTENT_ROOT="$STANDALONE_BINARY"
+  RESOURCE_ROOT="$STANDALONE_BINARY"
+
+else
+  fail "Internal Error: Test did not assign an archive or a binary value."
+fi
 
 # Parse any environmental variables passed into bash arrays for use within the
 # sourced verification scripts.
