Resolved most of the review comments

diff --git a/tools/bundletool/process_and_sign.sh.template b/tools/bundletool/process_and_sign.sh.template
--- a/tools/bundletool/process_and_sign.sh.template
+++ b/tools/bundletool/process_and_sign.sh.template
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 set -eu
 
 # The path where the archive should be created, including the name of the
@@ -31,36 +31,40 @@ if [[ -n "$POST_PROCESSOR" ]]; then
 fi
 
 # Strip out any unnecessary slices from embedded dynamic frameworks to save space
-for i in "$WORK_DIR"/*.app; do
+temp_basename=`basename $0`
+temp_file=`mktemp -q /tmp/${temp_basename}.XXXXXX`
+if [ $? -ne 0 ]; then
+       echo "error: Can't create temp file, exiting..." >&2
+       exit 1
+fi
+for app in "$WORK_DIR"/*.app; do
     # Lets figure out what slices the app has
-    app_name=$(basename $i .app)
-    slices=$(xcrun lipo -info $i/$app_name | cut -d: -f3)
+    app_name=$(basename "$app" .app)
+    app_slices=$(xcrun lipo -info "$app/$app_name" | cut -d: -f3)
 
     # Now lets make sure any included frameworks match
-    for f in $i/Frameworks/*.framework; do
+    for framework in "$app"/Frameworks/*.framework; do
         # We need to check we have overlapping architectures
-        framework_name=$(basename $f .framework)
-        framework_slices=$(xcrun lipo -info $f/$framework_name | cut -d: -f3)
-        # Sanity check that the framework has at least the slices the app has
-        for s in $slices ; do
-            echo $framework_slices | grep -q $s
-            if [ $? -ne 0 ]; then
-                echo "App has slice $s, but $f does not. Aborting..."
-                exit -1
-            fi
-        done
+        framework_name=$(basename "$framework" .framework)
+        framework_slices=$(xcrun lipo -info "$framework"/"$framework_name" | cut -d: -f3)
+        
+        # The normal case should be that the framework and app have exactly the same slices.
+        # Lets check that and skip processing if that is the case.
+        if [ "$app_slices" == "$framework_slices" ]; then
+            continue;
+        fi
 
+        lipo_args=""
         # Now make the framework match the slices the app has
-        for s in $slices ; do
-            lipo_args="$lipo_args -extract $s"
+        for slice in $app_slices ; do
+            lipo_args="$lipo_args -extract $slice"
         done
-        xcrun lipo $f/$framework_name $lipo_args -output $temp_file
+        xcrun lipo "$framework"/"$framework_name" $lipo_args -output "$temp_file"
         if [ $? -ne 0 ]; then
-            echo lipo failed, aborting...
+            echo "error: lipo of $framework_name failed" >&2
             exit 1
         fi
-        file $temp_file
-        mv $temp_file $f/$framework_name
+        mv $temp_file "$framework"/"$framework_name"
     done
 done
 
